---

- name: Check if backup folder exists or not
  stat:
    path: "{{ backup_path }}/Release_{{ git_tag }}_{{ existingBuildNumber }}/{{ item.name }}/"
  register: old_build_folder_stat
  with_items:
    - "{{ node_name }}"

- name: Specific to fresh install - Check if node name is present in backup 
  stat: 
    path: "{{ backup_path }}/Release_{{ git_tag }}_existingBuildNumber/{{ item.0.name }}"
  register: old_node_name_stat
  when: not "{{ item.1.stat.exists }}" == "1"
  with_together: 
    - "{{ node_name }}"  
    - "{{ old_build_folder_stat.results }}"

- name: Remove the builds folder before restoring the backup
  file:
    path: "{{ item.0.tomcat_path }}"
    state: absent
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}"

- name: Compress the backup folder
  shell: cd "{{ backup_path }}/" ; tar -cvzf "Release_{{ git_tag }}_{{ existingBuildNumber }}.tar.gz" "Release_{{ git_tag }}_{{ existingBuildNumber }}/"
  when: old_node_name_stat.results.0.stat.exists or old_build_folder_stat.results.0.stat.exists

- name: Replace the build folder with the {{ git_tag }}_{{ existingBuildNumber }} backup
  shell: mv "{{ backup_path }}Release_{{ git_tag }}_{{ existingBuildNumber }}/{{ item.0.name }}" "{{ item.0.tomcat_path }}"
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}"

- name: Replace the releaseVersion file
  shell: cp "{{ backup_path }}Release_{{ git_tag }}_{{ existingBuildNumber }}/releaseVersion.properties" "{{ build_path }}"
  when: "{{ item.1.stat.exists }}"
  with_together:
   - "{{ node_name }}"
   - "{{ old_build_folder_stat.results }}"

- name: verify permissions to build folder(tomcat folder)
  file:
    path: "{{ item.0.tomcat_path }}"
    state: directory
    owner: webtech
    group: analytics
    mode: 0775
    recurse: yes
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}"

- name: verify permissions to releaseVersion.properties file
  file:
    path: "{{ build_path }}/releaseVersion.properties"
    state: file
    owner: webtech
    group: analytics
    mode: 0775
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}"