---

- name: Check if build folder(backup) exists or not
  stat: 
    path: "{{ backup_path }}/Release_{{ git_tag }}_{{ existingBuildNumber }}/{{ product }}/"
  register: old_build_folder_stat
  with_items: "{{ node_name }}"

- name: Specific to fresh install - Check if node name is present in backup 
  stat: 
    path: "{{ backup_path }}/Release_{{ git_tag }}_existingBuildNumber/{{ product }}"
  register: old_node_name_stat
  when: not "{{ item.1.stat.exists }}" == "1"
  with_together: 
    - "{{ node_name }}"  
    - "{{ old_build_folder_stat.results }}"

- debug:
    var: old_build_folder_stat.results

- name: Remove the builds folder(new) before restoring the backup
  file:
    path: "{{ item.0.application_node_path }}"
    state: absent
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}" 

- name: Compress the backup folder
  shell: cd "{{ backup_path }}/" ; tar -cvzf "Release_{{ git_tag }}_{{ existingBuildNumber }}.tar.gz" "Release_{{ git_tag }}_{{ existingBuildNumber }}/"
  when: old_node_name_stat.results.0.stat.exists or old_build_folder_stat.results.0.stat.exists

- name: Replace build folder with the {{ git_tag }}_{{ existingBuildNumber }} backup
  shell: mv "{{ backup_path }}/Release_{{ git_tag }}_{{ existingBuildNumber }}/{{ product }}/" "{{ item.0.application_node_path }}/"
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}"

- name: delete old backup
  file:
    path: "{{ backup_path }}/Release_{{ git_tag }}_{{ existingBuildNumber }}/"
    state: absent
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}"

- name: verify permissions to build folder
  file:
    path: "{{ item.0.application_node_path }}"
    state: directory
    owner: webtech
    group: analytics
    mode: 0775
    recurse: yes
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ old_build_folder_stat.results }}"