---

- name: remove builds.zip from local machine
  local_action:
    module: file
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ build_local_server_path }}"
    - "{{ tomcat_local_server_path }}"	
  ignore_errors: true

- name: remove git folder from local machine
  local_action:
    module: file
    path: "{{ local_git_path }}"
    state: absent
  ignore_errors: true

- name: remove git_key folder from local machine
  local_action:
    module: file
    path: "{{ git_key }}"
    state: absent
  ignore_errors: true