---
# Pull all the product related config from git
- name: copy git_key file
  local_action:
    module: copy
    src: files/git_key
    dest: "{{ git_key }}"
    owner: jenkins
    mode: 400

- local_action:
    module: file
    path: /tmp/git/
    state: directory

- local_action:
    module: git
    repo: "{{ git_url }}"
    dest: /tmp/git/{{ product }}/
    version: "{{ git_tag }}"
    clone: yes
    accept_hostkey: yes
    key_file: "{{ git_key }}"