---

- name: Check if tomcat is present or not
  stat: path="{{ item.tomcat_path }}"
  register: tomcat_exists
  with_items: "{{ node_name }}"

- name: Create backup
  file:
    path: "{{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber.stdout }}/{{ item.name }}"
    state: directory
    recurse: yes
    mode: 0775
    owner: webtech
    group: analytics
  with_items:
    - "{{ node_name }}"

- name: Backup the existing folder(entire tomcat with build)
  command: mv "{{ item.0.tomcat_path }}/" "{{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber.stdout }}/"
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ tomcat_exists.results }}"

- name: Backup releaseVersion.properties file
  command: cp "{{ build_path }}releaseVersion.properties" "{{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber.stdout }}/"
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ tomcat_exists.results }}"

- name: Clear the old setup
  file:
    path: "{{ item.0.tomcat_path }}/"
    state: absent
  when: "{{ item.1.stat.exists }}"
  with_together:
    - "{{ node_name }}"
    - "{{ tomcat_exists.results }}"


- name: Create new tomcat folder(node in this case)
  file:
    path: "{{ item.0.tomcat_path }}"
    state: directory
    recurse: yes
    owner: webtech
    group: analytics
    mode: 0775
  with_together:
    - "{{ node_name }}"
    - "{{ tomcat_exists.results }}"

- name: Extract tomcat
  unarchive:
    src: "{{ tomcat_local_server_path }}{{ tomcat_artifact_id }}-{{ item.tomcat_version }}.zip"
    dest: "{{ item.tomcat_path }}/"
    owner: webtech
    group: analytics
    mode: '0775'
    remote_src: 'no'
  with_items:
    - "{{ node_name }}"

- name: Modify the required shell scripts
  template:
    src: "{{ local_git_path }}{{ config_env }}/{{ item.1 }}.j2"
    dest: "{{ item.0.tomcat_path }}/bin/{{ item.1 }}.sh"
    owner: webtech
    group: analytics
    mode: '0775'
    backup: yes
  with_subelements:
    - "{{ node_name }}"
    - shell_scripts

- name: Modify the server.xml
  template:
    src: "{{ build_local_server_path }}{{ build_folder }}/templates/{{ item.server_xml_name }}"
    dest: "{{ item.tomcat_path }}/conf/server.xml"
    owner: webtech
    group: analytics
    mode: '0775'
    backup: yes
  with_items:
    - "{{ node_name }}"

- name: Create additional required folders
  file:
    path: "{{ item.0.tomcat_path }}/"
    state: directory
    owner: webtech
    group: analytics
    mode: 0775
  with_subelements:
    - "{{ node_name }}"
    - required_folders
  ignore_errors: true