---

- name: check if build exists
  stat:
    path: "{{ jar_location }}/{{ build_folder }}"
  register: old_build_folder

- name: create backup folder
  file:
    path: "{{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber.stdout }}"
    state: directory
    owner: webtech
    group: analytics
    mode: '0775'
  when: old_build_folder.stat.exists

- name: Copy existing build to backup location
  shell: "mv {{ jar_location }}/{{ build_folder }} {{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber.stdout }}/{{ item.name }}/"
  when: old_build_folder.stat.exists
  with_items: "{{ node_name }}"

- name: Delete the existing build
  file:
    path: "{{ jar_location }}/{{ build_folder }}"
    state: absent
  when: old_build_folder.stat.exists

- name: Copy existing shell files to backup location
  shell: "mv {{ shell_path }} {{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber.stdout }}/{{ item.name }}/"
  when: old_build_folder.stat.exists
  with_items: "{{ node_name }}"

- name: Delete the existing shell scripts
  file:
    path: "{{ shell_path }}"
    state: absent
  when: old_build_folder.stat.exists