---

#Configuration validation
- name: create a validation folder
  file: path="/tmp/nginxvalidate/vhosts" state=directory recurse=yes 

- name: modify the nginx-{{ product }} config
  template:
    src: "{{ build_local_server_path }}builds/templates/{{ product }}_nginx_conf.j2"
    dest: "/tmp/nginxvalidate/vhosts/{{ product }}.conf"
    owner: webtech
    group: analytics
    mode: '0775'

- name: Copy nginx.conf to validation folder
  copy:
    src: "/etc/nginx/{{ item }}"
    dest: "/tmp/nginxvalidate/{{ item }}"
    remote_src: true
  with_items:
    - nginx.conf
    - fastcgi_params
    - mime.types


- name: Validate nginx configiguration
  shell: nginx -t -c /tmp/nginxvalidate/nginx.conf

#Backup
- name: Create backup folder
  file:
    path: /etc/nginx/old_config/{{ product }}/{{ git_tag }}_{{ NewBuildNumber.stdout }}/
    state: directory
    owner: webtech
    group: analytics        
    recurse: yes
    mode: 0775

- name: check if nginx vhost file exists or not
  stat: 
    path: /etc/nginx/vhosts/{{ product }}.conf
    get_md5: yes
  register: nginx_vhost_path_op

- name: Backup {{ product }} vhost configuration file
  copy:
    src: "/etc/nginx/vhosts/{{ product }}.conf"
    dest: "/etc/nginx/old_config/{{ product }}/{{ git_tag }}_{{ NewBuildNumber.stdout }}/"
    remote_src: true	
  when: nginx_vhost_path_op.stat.exists



#Check old and new config of nginx
- name: check new nginx vhost config
  stat:
    path: "/tmp/nginxvalidate/vhosts/{{ product }}.conf"
    get_md5: yes
  register: nginx_vhost_New_op

- name: check new nginx config
  stat:
    path: "/tmp/nginxvalidate/nginx.conf"
    get_md5: yes
  register: nginx_New_op

- name: check existing nginx config
  stat:
    path: "/etc/nginx/nginx.conf"
    get_md5: yes
  register: nginx_Old_op

- set_fact:
   nginx_vhost_old_md5: "emptyValue"

- set_fact:
   nginx_vhost_old_md5: "{{ nginx_vhost_path_op.stat.md5 }}"  
  when: nginx_vhost_path_op.stat.exists

- name: Replace the vhost configuration for {{ product }} product with the validated file
  copy: 
    src: "/tmp/nginxvalidate/vhosts/{{ product }}.conf" 
    dest: "/etc/nginx/vhosts/{{ product }}.conf"
    owner: webtech
    group: analytics
    mode: 0775
    remote_src: true
  when: nginx_vhost_old_md5 != nginx_vhost_New_op.stat.md5
  register: nginxVhostChange

- name: Replace the nginx.conf with the validated file
  copy: 
    src: "/tmp/nginxvalidate/nginx.conf" 
    dest: "/etc/nginx/nginx.conf"
    mode: 0644
    remote_src: true
  when: nginx_Old_op.stat.md5 != nginx_New_op.stat.md5
  register: nginxChange

- name: restart nginx
  service: 
    name: nginx
    state: restarted
  when: nginxVhostChange.changed or nginxChange.changed

- name: change permissions of var/cache/nginx
  file:
    path: /var/cache/nginx/
    state: directory
    recurse: yes
    mode: 0775

- name: delete the created validation folder
  file:
    path: /tmp/nginxvalidate
    state: absent