---

- name: check if build exists
  stat:
    path: "{{ jar_location }}"
  register: old_build_folder

- name: create backup folder
  file:
    path: "{{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber }}"
    state: directory
    owner: webtech
    group: analytics
    mode: '0775'
  when: old_build_folder.stat.exists
  
- name: Copy existing build to backup location
  archive:
    path: "{{ application_node_path }}"
    dest: "{{ backup_path }}Release_{{ git_tag }}_{{ NewBuildNumber }}/{{ application_node_path | dirname | basename }}.zip"
    format: zip
    mode: "0755"
    owner: "webtech"
    group: "analytics"
  when: old_build_folder.stat.exists
  with_items:
    - "{{ node_name }}"

- name: Delete the existing build
  file:
    path: "{{ application_node_path }}"
    state: absent
  when: old_build_folder.stat.exists