---

- name: Create Build folder
  file:
    path: "{{ item.application_node_path }}"
    state: directory
    owner: webtech
    group: analytics
    mode: '0775'
  with_items:
    - "{{ node_name }}"

- name: create required folders
  file:
    path: "{{ item.0.application_node_path }}/{{ item.1 }}"
    state: directory
    owner: webtech
    group: analytics
    mode: '0775'
  with_subelements:
    - "{{ node_name }}"
    - build_required_folders

- copy:
    src: "{{ build_local_server_path }}/builds/build/{{ product }}.jar"
    dest: "{{ item.jar_location }}"
    owner: webtech
    group: analytics
    mode: '0775'
  with_items:
    - "{{ node_name }}"
    
- name: Copy the startup jar
  copy:
    src: "{{ build_local_server_path }}/builds/build/{{ item.1 }}"
    dest: "{{ item.0.application_node_path }}/bin/"
    owner: webtech
    group: analytics
    mode: '0775'
  when: item.0.name == "service_node"
  with_subelements:
    - "{{ node_name }}"
    - startup_jars
    
- name: Copy the releaseVersion.properties file
  copy:
    src: "{{ build_local_server_path }}{{ releaseVersion_properties_path }}releaseVersion.properties"
    dest: "{{ item.application_node_path }}/"
    owner: webtech
    group: analytics
    mode: '0775'
  with_items:
    - "{{ node_name }}"