---

- hosts: all
  become: yes
  remote_user: webtech
  vars_files:
    - vars/main-vars.yml
  pre_tasks:
    - include_tasks: tasks/git.yml
      run_once: yes
    - name: including git vars - configurations
      local_action:
        module: include_vars
        dir: '{{ local_git_path }}{{ config_env }}/'
        files_matching: '.yml'
      run_once: yes
    - include_tasks: tasks/get_build_version.yml
      #when: pkg.find('tomcat') != -1
      #run_once: yes
    - meta: refresh_inventory
  roles:
    - { role: properties_rollback, when: pkg.find('properties') != -1 }
    - { role: shell_rollback, when: pkg.find('shell_executables') != -1 }
    - { role: db_flyway_rollback, when: pkg.find('db_flyway_rollback') != -1 }
    - { role: node_rollback, when: pkg.find('node_apps') != -1 }
  post_tasks:
    - include_tasks: tasks/remove_old_files.yml
      with_items:
        - "{{ nodeList }}"
      loop_control:
        loop_var: node_name
