---

#-------------HA------------#
- name: checking for ha lock file
  stat:
    path: /tmp/haproxy_temp.lock
  register: ha
- debug:
    msg:
      - "##############################################################################################################"
      - ""
      - "    HA configuration failure, lock file present please delete it, /tmp/haproxy_temp.lock                      "
      - ""
      - "##############################################################################################################"
  when: ha.stat.exists

#----------NGINX------------#
- name: checking for nginx lock file
  stat:
    path: /tmp/nginx_temp.lock
  register: nginx
- debug:
    msg:
      - "#############################################################################################################"
      - ""
      - "   Nginx configuration failure, lock file present please delete it, /tmp/nginx_temp.lock                     "
      - ""
      - "#############################################################################################################"
  when: nginx.stat.exists

#-------------PHP-------------#
- name: checking for php lock file
  stat:
    path: /tmp/php_temp.lock
  register: php
- debug:
    msg:
      - "#############################################################################################################"
      - ""
      - "    PHP configuration failure, lock file present please delete it, /tmp/php_temp.lock                        "
      - ""
      - "#############################################################################################################"
  when: php.stat.exists

#-----------TOMCAT----------#
- name: checking for tomcat lock file
  stat:
    path: "/U01/{{ product }}/tomcat_temp.lock"
  register: tomcat
- debug:
    msg:
      - "#############################################################################################################"
      - ""
      - "    Tomcat configuration failure, lock file present please delete it, /U01/{{ product }}/tomcat_temp.lock    "
      - ""
      - "#############################################################################################################"
  when: tomcat.stat.exists

#---------PROPERTIES-----------#
- name: checking for properties lock file
  stat:
    path: "/U01/{{ product }}/properties_temp.lock"
  register: properties
- debug:
    msg:
      - "##################################################################################################################"
      - ""
      - "    Properties configuration failure, lock file present please delete it, /U01/{{ product }}/properties_temp.lock "
      - ""
      - "##################################################################################################################"
  when: properties.stat.exists

#--------------DB-------------#
- name: checking for DB lock file
  stat:
    path: "/U01/{{ product }}/DB_upgrade_temp.lock"
  register: DB
- debug:
    msg:
      - "#############################################################################################################"
      - ""
      - "    Database upgrade failure, lock file present please delete it, /U01/{{ product }}/DB_upgrade_temp.lock    "
      - ""
      - "#############################################################################################################"
  when: DB.stat.exists

- name: setting flag
  set_fact:
    flag: true
  when: ha.stat.exists or nginx.stat.exists or php.stat.exists or tomcat.stat.exists or properties.stat.exists or DB.stat.exists
- name: setting flag
  set_fact:
    flag: false
- name: abort deployment if any lock file exists
  fail:
    msg: "Configuration failure, Lock files found, please delete"
  when: flag == true